=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ClickSend::DefaultSendersApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DefaultSendersApi' do
  before do
    # run before each test
    @api_instance = ClickSend::DefaultSendersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DefaultSendersApi' do
    it 'should create an instance of DefaultSendersApi' do
      expect(@api_instance).to be_instance_of(ClickSend::DefaultSendersApi)
    end
  end

  # unit tests for create_default_sender
  # Create Default Sender
  # Creates a new default sender configuration to automate the selection of compliant SenderIDs. By configuring a default sender you no longer need to define the &#x60;sender_id&#x60; string when sending SMS messages. The default sender will be picked up automatically.  For more information on Sender IDs, please refer to [What is a Sender ID or Sender Number?](https://help.clicksend.com/article/4kgj7krx00-what-is-a-sender-id-or-sender-number)
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CreateDefaultSenderRequest] :create_default_sender_request 
  # @return [CreateDefaultSender]
  describe 'create_default_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_default_sender
  # Delete Default Sender
  # Removes a specified default sender setting.  If you don&#39;t configure a default sender and leave the &#x60;sender_id&#x60; string blank when sending an SMS, Smart Assign will pick the best suitable, compliant, available SenderID for you.
  # @param default_sender_id The ID of the default sender to delete
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [nil]
  describe 'delete_default_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_default_sender_details
  # Get Default Sender Details
  # Retrieve detailed information about a specific default sender configuration
  # @param default_sender_id The ID of the default sender to retrieve
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [GetDefaultSenderDetails]
  describe 'get_default_sender_details test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for get_default_senders_list
  # Get List of Default Senders
  # Retrieve a list of default senders for the current user
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [String] :offset Page (offset) to be used for pagination
  # @option opts [Integer] :per_page Size of the page in pagination
  # @option opts [String] :sort_by Parameter to sort the results by
  # @option opts [String] :sort_direction Direction of sorting
  # @return [GetDefaultSendersList]
  describe 'get_default_senders_list test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for list_compliant_sender_types
  # List Compliant Sender Types
  # Retrieves the list of compliant sender types for specific countries
  # @param filter_product_type Type of the product
  # @param [Hash] opts the optional parameters
  # @option opts [Array<String>] :filter_country_code_index Array of recipient country codes (ISO 3166-1 alpha-2). If not specified, will get all compliant sender types for all countries. Replace &#x60;{index}&#x60; with the appropriate index value.  &lt;small&gt;Example:&lt;/small&gt; &lt;small&gt;&lt;code style&#x3D;\&quot;color: #424242;\&quot;&gt;filter[country_code][0]&#x3D;US&amp;filter[country_code][1]&#x3D;AU&lt;/code&gt;&lt;/small&gt; 
  # @return [ListCompliantSenderTypes200Response]
  describe 'list_compliant_sender_types test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_default_sender
  # Update Default Sender
  # Updates the details of an existing default sender configuration.  For more information on Sender IDs, please refer to [What is a Sender ID or Sender Number?](https://help.clicksend.com/article/4kgj7krx00-what-is-a-sender-id-or-sender-number)
  # @param default_sender_id The ID of the default sender to update
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [UpdateDefaultSenderRequest] :update_default_sender_request 
  # @return [UpdateDefaultSender]
  describe 'update_default_sender test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
