=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ClickSend::SmsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SmsApi' do
  before do
    # run before each test
    @api_instance = ClickSend::SmsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SmsApi' do
    it 'should create an instance of SmsApi' do
      expect(@api_instance).to be_instance_of(ClickSend::SmsApi)
    end
  end

  # unit tests for calculate_sms_price
  # Calculate SMS Price
  # Use this endpoint to calculate the price of sending messages. The cost of sending messages varies based on the &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\&quot; target&#x3D;\&quot;_blank\&quot;&gt;type&lt;/a&gt; and length of the message.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CalculateSmsPriceRequest] :calculate_sms_price_request 
  # @return [CalculateSmsPrice]
  describe 'calculate_sms_price test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cancel_all_sms
  # Cancel All SMS
  # Use this endpoint to cancel all scheduled SMS. To cancel only one scheduled SMS, use the **Cancel SMS** endpoint.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CancelAllSmsRequest] :cancel_all_sms_request 
  # @return [CancelAllSms]
  describe 'cancel_all_sms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for cancel_sms
  # Cancel SMS
  # Use this endpoint to cancel a specific scheduled SMS. Unlike the **Cancel All SMS** endpoint, which cancels all scheduled SMS, this endpoint only cancels one specified scheduled SMS.  Specify the scheduled SMS to cancel by providing its _message_id_.
  # @param message_id The _message_id_ of the scheduled SMS to cancel.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [CancelSms]
  describe 'cancel_sms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_sms_delivery_receipt_rule
  # Create SMS Delivery Receipt Rule
  # _Create sms delivery receipt automations_  Create sms delivery receipt automations  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | rule_name | string | true | none | Rule Name. | | match_type | number | true | none | Match Type. 0&#x3D;All reports. | | action | string | true | none | Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). | | action_address | string | true | none | Action address. | | enabled | number | true | none | Enabled: Disabled&#x3D;0 or Enabled&#x3D;1. |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CreateSmsDeliveryReceiptRuleRequest] :create_sms_delivery_receipt_rule_request 
  # @return [CreateSmsDeliveryReceiptRule]
  describe 'create_sms_delivery_receipt_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_sms_inbound_automation
  # Create SMS Inbound Automation
  # _Create new inbound sms automation_  Create new inbound sms automation  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | dedicated_number | string | true | none | Decicated Number. Can be &#39;\\*&#39; to apply to all numbers. | | rule_name | string | true | none | Rule Name. | | message_search_type | number | true | none | Message Search Type: 0&#x3D;Any message, 1&#x3D;starts with, 2&#x3D;contains, 3&#x3D;does not contain. | | message_search_term | string | true | none | Message search term. | | action | string | true | none | Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). | | action_address | string | true | none | Action address. | | enabled | number | true | none | Enabled: Disabled&#x3D;0 or Enabled&#x3D;1. | | webhook_type | string | false | Required when action &#x3D; URL only | Set as post, get, or json to change the format of the request sent. |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CreateSmsInboundAutomationRequest] :create_sms_inbound_automation_request 
  # @return [CreateSmsInboundAutomation]
  describe 'create_sms_inbound_automation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_sms_template
  # Create SMS Template
  # Use this endpoint to create a SMS template that you can use for sending SMS.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CreateSmsTemplateRequest] :create_sms_template_request 
  # @return [CreateSmsTemplate]
  describe 'create_sms_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_test_inbound_sms
  # Create Test Inbound SMS
  # Use this endpoint to generate and send a test &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/ik4hw5xu35-can-i-receive-inbound-sms-to-my-url\&quot; target&#x3D;\&quot;_blank\&quot;&gt;inbound SMS&lt;/a&gt; to your webhook URL. Inbound SMS are messages sent by your recipient to you.  This test endpoint allows you to verify that the inbound SMS is correctly sent to your webhook URL.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CreateTestInboundSmsRequest] :create_test_inbound_sms_request 
  # @return [CreateTestInboundSms]
  describe 'create_test_inbound_sms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for create_test_sms_receipt
  # Create Test SMS Receipt
  # Use this endpoint to generate and send a test &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/49eq1qdcui-how-do-i-receive-sms-delivery-receipts-delivery-status-updates\&quot; target&#x3D;\&quot;_blank\&quot;&gt;SMS delivery receipt&lt;/a&gt; to your webhook URL. When you send an SMS, a delivery receipt is generated and can be received at your webhook URL. This test endpoint allows you to verify that the receipt is correctly sent to your webhook URL.  Additionally, you can obtain SMS receipts by setting the webhook URL to **poll** and periodically calling the **View SMS Receipt** endpoint to check for new receipts. This process is known as _polling_.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CreateTestSmsReceiptRequest] :create_test_sms_receipt_request 
  # @return [CreateTestSmsReceipt]
  describe 'create_test_sms_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sms_delivery_receipt_rule
  # Delete SMS Delivery Receipt Rule
  # _Delete sms delivery receipt automation_  Delete sms delivery receipt automation  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | receipt_rule_id | path | integer(int32) | true | Receipt rule id |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param receipt_rule_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [DeleteSmsDeliveryReceiptRule]
  describe 'delete_sms_delivery_receipt_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sms_inbound_automation
  # Delete SMS Inbound Automation
  # _Delete inbound sms automation_  Delete inbound sms automation  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | inbound_rule_id | path | integer(int32) | true | Inbound rule id |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param inbound_rule_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [DeleteSmsInboundAutomation]
  describe 'delete_sms_inbound_automation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for delete_sms_template
  # Delete SMS Template
  # Use this endpoint to delete a &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/9z9uloaz8y-sms-templates-for-different-industries\&quot; target&#x3D;\&quot;_blank\&quot;&gt;SMS template&lt;/a&gt;. Specify the SMS template to delete by providing its _template_id_.
  # @param template_id The ID of the template to delete.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [DeleteSmsTemplate]
  describe 'delete_sms_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for export_sms_history
  # Export SMS History
  # Use this endpoint to create a download link of your SMS history. You can filter the SMS history result using the query parameters.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [String] :filename The filename of the result. It should be in the .csv format.
  # @option opts [Integer] :page The page number to retrieve. Use this parameter to navigate through the [pagination](/#pagination) results. The default value is 1.
  # @option opts [Integer] :limit The number of items to return per page. This parameter controls the size of each page of results. The default value is 15.
  # @option opts [String] :q Allows filtering of results based on your search criteria. The query should be in the format &#x60;field_name:value&#x60;.  1. **Field Name**: The field within the SMS history you want to filter by. You can use the following fields:          - _Status_: The status of the SMS. Available values for status are: Queued, Completed, Scheduled, WaitApproval, Failed, Cancelled, CancelledAfterReview, Received, Sent.              - _To_: The recipient of the SMS.              - _from_: The sender of the SMS.              - _subaccount_id_: The sub-account identifier.              - _message_id_: The ID of your SMS.          2. **Value**: The text or keyword you&#39;re searching for within the specified field. If left empty after the colon, the filter will look for all templates with any value in the **Field Name**.             For example, if you are searching for a SMS with the status of _Scheduled_, the final query would look like this:    &#x60;q&#x3D;status:Scheduled&#x60;  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;div&gt;   &lt;p&gt;Some characters have to be encoded. For example, if you are searching for SMS sent from the phone number +61437085284, your search query q would be:&lt;br/&gt;&lt;/p&gt;     &lt;ul&gt;       &lt;li&gt;q&#x3D;from:%2B61437085284&lt;/li&gt;     &lt;/ul&gt;     &lt;p&gt;You can use the &lt;a href&#x3D;\&quot;https://www.urlencoder.org/\&quot; target&#x3D;\&quot;_blank\&quot;&gt;URL encoder&lt;/a&gt; to encode the text. If a character is not an alphanumeric character (A-Z, a-z, 0-9), it is typically either reserved or unsafe and should be encoded.&lt;/p&gt;   &lt;/div&gt; &lt;/div&gt;
  # @option opts [String] :order_by Specifies the field and order to sort the results by. The value is composed of the field name followed by a colon and the sort direction (asc for ascending or desc for descending).  The default sort order is by date in ascending order. You can use the following fields:    - _date_    - _username_   - _from_    - _to_   - _status_    - _body_  For example, if you want to order by the most recently sent SMS, you should sort by date in descending order. The query would look like this:    &#x60;order_by&#x3D;date:desc&#x60;
  # @option opts [Integer] :date_from Start date to filter results. It should be in &lt;a href&#x3D;\&quot;http://help.clicksend.com/what-is-a-unix-timestamp\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Unix format&lt;/a&gt;.
  # @option opts [Integer] :date_to End date to filter results. It should be in &lt;a href&#x3D;\&quot;http://help.clicksend.com/what-is-a-unix-timestamp\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Unix format&lt;/a&gt;.
  # @return [ExportSmsHistory]
  describe 'export_sms_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_inbound_sms_as_read
  # Mark Inbound SMS as Read
  # Use this endpoint to mark all &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/ik4hw5xu35-can-i-receive-inbound-sms-to-my-url\&quot; target&#x3D;\&quot;_blank\&quot;&gt;inbound SMS&lt;/a&gt; as read. Inbound SMS that has been marked as read won’t be shown in the **View Inbound SMS** endpoint. You can still use the **View Specific Inbound SMS** endpoint to view inbound SMS marked as read.  In the request, you can optionally add a _date_before_ parameter to only mark inbound SMS sent before that date as read.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [MarkSmsReceiptAsReadRequest] :mark_sms_receipt_as_read_request 
  # @return [MarkInboundSmsAsRead]
  describe 'mark_inbound_sms_as_read test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_sms_receipt_as_read
  # Mark SMS Receipt As Read
  # Use this endpoint to mark all &lt;a target&#x3D;\&quot;_blank\&quot; href&#x3D;\&quot;https://help.clicksend.com/article/49eq1qdcui-how-do-i-receive-sms-delivery-receipts-delivery-status-updates\&quot;&gt;SMS delivery receipts&lt;/a&gt; as read. Delivery receipts that have been marked as read won’t be shown in the **View SMS Receipts** endpoint.  You can still use the **View Specific SMS Receipt** endpoint to view delivery receipts marked as read. In the request, you can optionally add a _date_before_ parameter to only mark receipts sent before that date as read
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [MarkSmsReceiptAsReadRequest] :mark_sms_receipt_as_read_request 
  # @return [MarkSmsReceiptAsRead]
  describe 'mark_sms_receipt_as_read test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for mark_specific_inbound_sms_message_as_read
  # Mark Specific Inbound SMS Message As Read
  # Use this endpoint to mark a specific &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/ik4hw5xu35-can-i-receive-inbound-sms-to-my-url\&quot; target&#x3D;\&quot;_blank\&quot;&gt;inbound SMS&lt;/a&gt; as read. Unlike the **View Inbound SMS** endpoint, which marks all inbound SMS as read,  this endpoint only marks one specified inbound SMS. Specify the SMS to be marked as read by providing its _message_id_.
  # @param message_id The message_id of the inbound SMS to mark as read.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;     When you receive an inbound message, you will get two parameters: &lt;em&gt;original_message_id&lt;/em&gt; and &lt;em&gt;message_id&lt;/em&gt;:   &lt;/p&gt;   &lt;ul&gt;     &lt;li&gt;&lt;em&gt;original_message_id&lt;/em&gt;: This is the ID of the outbound message sent to the recipient&lt;/li&gt;     &lt;li&gt;&lt;em&gt;message_id&lt;/em&gt;: This is the ID of the inbound message sent by the recipient.&lt;/li&gt;   &lt;/ul&gt; &lt;/div&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [MarkSpecificInboundSmsMessageAsRead]
  describe 'mark_specific_inbound_sms_message_as_read test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for send_sms
  # Send SMS
  # Use this endpoint to send messages to your recipients, either as phone numbers or contacts from your contact list.  The sender of the message (&lt;a href&#x3D;\&quot;https://help.clicksend.com/article/4kgj7krx00-what-is-a-sender-id-or-sender-number\&quot; target&#x3D;\&quot;_blank\&quot;&gt;&lt;strong&gt;Sender ID&lt;/strong&gt;&lt;/a&gt;) can be a shared number, a dedicated number, alpha tag (business name), or your own number.  You can send messages both locally and globally, subject to the country restrictions. The cost of sending messages varies based on the &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\&quot; target&#x3D;\&quot;_blank\&quot;&gt;type&lt;/a&gt; and length of the message.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [SendSmsRequest] :send_sms_request 
  # @return [SendSms]
  describe 'send_sms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_sms_delivery_receipt_rule
  # Update SMS Delivery Receipt Rule
  # _Update sms delivery receipt automation_  Update sms delivery receipt automation  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | receipt_rule_id | path | integer(int32) | true | Receipt rule id |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | rule_name | string | true | none | Rule Name. | | match_type | number | true | none | Match Type. 0&#x3D;All reports. | | action | string | true | none | Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). | | action_address | string | true | none | Action address. | | enabled | number | true | none | Enabled: Disabled&#x3D;0 or Enabled&#x3D;1. |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param receipt_rule_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CreateSmsDeliveryReceiptRuleRequest] :create_sms_delivery_receipt_rule_request 
  # @return [UpdateSmsDeliveryReceiptRule]
  describe 'update_sms_delivery_receipt_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_sms_inbound_automation
  # Update SMS Inbound Automation
  # _Update inbound sms automation_  Update inbound sms automation  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | inbound_rule_id | path | integer(int32) | true | Inbound rule id |  ### Properties  | Name | Type | Required | Restrictions | Description | | --- | --- | --- | --- | --- | | dedicated_number | string | true | none | Dedicated Number. Can be &#39;\\*&#39; to apply to all numbers. | | rule_name | string | true | none | Rule Name. | | message_search_type | number | true | none | Message Search Type: 0&#x3D;Any message, 1&#x3D;starts with, 2&#x3D;contains, 3&#x3D;does not contain. | | message_search_term | string | true | none | Message search term. | | action | string | true | none | Action to be taken (AUTO_REPLY, EMAIL_USER, EMAIL_FIXED, URL, SMS, POLL, GROUP_SMS, MOVE_CONTACT, CREATE_CONTACT, CREATE_CONTACT_PLUS_EMAIL, CREATE_CONTACT_PLUS_NAME_EMAIL CREATE_CONTACT_PLUS_NAME, SMPP, NONE). | | action_address | string | true | none | Action address. | | enabled | number | true | none | Enabled: Disabled&#x3D;0 or Enabled&#x3D;1. | | webhook_type | string | false | Required when action &#x3D; URL only | Set as post, get, or json to change the format of the request sent. |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param inbound_rule_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [UpdateSmsInboundAutomationRequest] :update_sms_inbound_automation_request 
  # @return [UpdateSmsInboundAutomation]
  describe 'update_sms_inbound_automation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for update_sms_template
  # Update SMS Template
  # Use this endpoint to update a &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/9z9uloaz8y-sms-templates-for-different-industries\&quot; target&#x3D;\&quot;_blank\&quot;&gt;SMS template&lt;/a&gt;.
  # @param template_id The ID of the template to update.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [CreateSmsTemplateRequest] :create_sms_template_request 
  # @return [UpdateSmsTemplate]
  describe 'update_sms_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_a_specific_inbound_sms_message
  # View a specific inbound SMS message
  # Use this endpoint to retrieve a specific inbound SMS, including those that have been marked as read.  Inbound SMS are messages sent by your recipient to you. This endpoint enables you to retrieve those inbound SMS.
  # @param original_message_id The _original_message_id_ of the inbound SMS to view. If the recipient replied with multiple messages, this endpoint returns the first inbound SMS received.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;     When you receive an inbound message, you will get two parameters: &lt;em&gt;original_message_id&lt;/em&gt; and &lt;em&gt;message_id&lt;/em&gt;:   &lt;/p&gt;   &lt;ul&gt;     &lt;li&gt;&lt;em&gt;original_message_id&lt;/em&gt;: This is the ID of the outbound message sent to the recipient&lt;/li&gt;     &lt;li&gt;&lt;em&gt;message_id&lt;/em&gt;: This is the ID of the inbound message sent by the recipient.&lt;/li&gt;   &lt;/ul&gt; &lt;/div&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [ViewASpecificInboundSmsMessage]
  describe 'view_a_specific_inbound_sms_message test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_a_specific_sms_template
  # View a Specific SMS Template
  # Use this endpoint to retrieve a &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/9z9uloaz8y-sms-templates-for-different-industries\&quot; target&#x3D;\&quot;_blank\&quot;&gt;SMS template&lt;/a&gt;. Specify which template to retrieve using the template ID.
  # @param template_id The ID of the template to retrieve
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [ViewASpecificSmsTemplate]
  describe 'view_a_specific_sms_template test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_inbound_sms
  # View Inbound SMS
  # Use this endpoint to retrieve &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/49eq1qdcui-how-do-i-receive-sms-delivery-receipts-delivery-status-updates\&quot; target&#x3D;\&quot;_blank\&quot;&gt;SMS delivery receipts&lt;/a&gt; sent by your recipient.  To be able to view receipts, add a &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/ut4ttdrrai-incoming-reply-sms-options\&quot;&gt;inbound rule&lt;/a&gt; with the Action set to **POLL** in the Dashboard, or use the [**Create SMS Inbound Automation**](/automations/sms/other/create-sms-inbound-automation) endpoint.  Control [pagination](/#pagination) with the _page_ and _limit_ query parameters to specify the page of results and the number of items returned.  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;p&gt;If you have multiple inbound rules set to &lt;strong&gt;POLL&lt;/strong&gt;, you will receive the inbound message multiple times.&lt;/p&gt; &lt;/div&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [Integer] :page The page number to retrieve. Use this parameter to navigate through the [pagination](/#pagination) results. The default value is 1.
  # @option opts [Integer] :limit The number of items to return per page. This parameter controls the size of each page of results. The default value is 15.
  # @return [ViewInboundSms]
  describe 'view_inbound_sms test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_sms_delivery_receipt_rule
  # View SMS Delivery Receipt Rule
  # _Get specific sms delivery receipt automation_  Get specific sms delivery receipt automation  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | receipt_rule_id | path | integer(int32) | true | Receipt rule id |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param receipt_rule_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [ViewSmsDeliveryReceiptRule]
  describe 'view_sms_delivery_receipt_rule test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_sms_delivery_receipt_rules
  # View SMS Delivery Receipt Rules
  # _Get all sms delivery receipt automations_  Get all sms delivery receipt automations  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | page | query | integer(int32) | false | Page number | | limit | query | integer(int32) | false | Number of records per page |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [ViewSmsDeliveryReceiptRules]
  describe 'view_sms_delivery_receipt_rules test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_sms_history
  # View SMS History
  # Use this endpoint to view previously sent SMS. You can filter the SMS history result using the query parameters.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [Integer] :page The page number to retrieve. Use this parameter to navigate through the [pagination](/#pagination) results. The default value is 1.
  # @option opts [Integer] :limit The number of items to return per page. This parameter controls the size of each page of results. The default value is 15.
  # @option opts [String] :q Allows filtering of results based on your search criteria. The query should be in the format &#x60;field_name:value&#x60;.  1. **Field Name**: The field within the SMS history you want to filter by. You can use the following fields:          - _Status_: The status of the SMS. Available values for status are: Queued, Completed, Scheduled, WaitApproval, Failed, Cancelled, CancelledAfterReview, Received, Sent.              - _To_: The recipient of the SMS.              - _from_: The sender of the SMS.              - _subaccount_id_: The sub-account identifier.              - _message_id_: The ID of your SMS.          2. **Value**: The text or keyword you&#39;re searching for within the specified field. If left empty after the colon, the filter will look for all templates with any value in the **Field Name**.             For example, if you are searching for a SMS with the status of Scheduled, the final query would look like this:    &#x60;q&#x3D;status:Scheduled&#x60;  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;div&gt;    &lt;p&gt;Some characters have to be encoded. For example, if you are searching for SMS sent from the phone number +61437085284, your search query q would be:&lt;br/&gt;&lt;/p&gt;     &lt;ul&gt;       &lt;li&gt;q&#x3D;from:%2B61437085284&lt;/li&gt;     &lt;/ul&gt;     &lt;p&gt;You can use the &lt;a href&#x3D;\&quot;https://www.urlencoder.org/\&quot; target&#x3D;\&quot;_blank\&quot;&gt;URL encoder&lt;/a&gt; to encode the text. If a character is not an alphanumeric character (A-Z, a-z, 0-9), it is typically either reserved or unsafe and should be encoded.&lt;/p&gt;   &lt;/div&gt; &lt;/div&gt;
  # @option opts [String] :order_by Specifies the field and order to sort the results by. The value is composed of the field name followed by a colon and the sort direction (_asc_ for ascending or _desc_ for descending).  The default sort order is by _date_ in ascending order. You can use the following fields:    - _date_   - _username_   - _from_    - _to_   - _status_   - _body_  For example, if you want to order by the most recently sent SMS, you should sort by date in descending order. The query would look like this:    &#x60;order_by&#x3D;date:desc&#x60;
  # @option opts [Integer] :date_from Start date to filter results. It should be in &lt;a href&#x3D;\&quot;http://help.clicksend.com/what-is-a-unix-timestamp\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Unix format&lt;/a&gt;.
  # @option opts [Integer] :date_to End date to filter results. It should be in &lt;a href&#x3D;\&quot;http://help.clicksend.com/what-is-a-unix-timestamp\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Unix format&lt;/a&gt;.
  # @return [ViewSmsHistory]
  describe 'view_sms_history test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_sms_inbound_automation
  # View SMS Inbound Automation
  # _Get specific inbound sms automation_  Get specific inbound sms automation  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | inbound_rule_id | path | integer(int32) | true | Inbound rule id |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param inbound_rule_id 
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [ViewSmsInboundAutomation]
  describe 'view_sms_inbound_automation test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_sms_inbound_automations
  # View SMS Inbound Automations
  # _Get all inbound sms automations_  Get all inbound sms automations  ### Parameters  | Parameter | In | Type | Required | Description | | --- | --- | --- | --- | --- | | page | query | integer(int32) | false | Page number | | limit | query | integer(int32) | false | Number of records per page |   Refer to [Status Codes](/#status-codes) for definitions of HTTP status code responses.   &lt;div style&#x3D;\&quot;background-color: #FF6A4B; padding: 10px; border-radius: 8px;\&quot;&gt;   &lt;span style&#x3D;\&quot;color: white;\&quot;&gt;This endpoint requires authentication,&lt;/span&gt;    &lt;a href&#x3D;\&quot;/docs/#authentication\&quot; style&#x3D;\&quot;color: white; text-decoration: underline;\&quot;&gt;more info...&lt;/a&gt; &lt;/div&gt;
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [ViewSmsInboundAutomations]
  describe 'view_sms_inbound_automations test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_sms_receipts
  # View SMS Receipts
  # Use this endpoint to retrieve &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/49eq1qdcui-how-do-i-receive-sms-delivery-receipts-delivery-status-updates\&quot; target&#x3D;\&quot;_blank\&quot;&gt;SMS delivery receipts&lt;/a&gt; sent by your recipient.  To be able to view receipts, add a &lt;a href&#x3D;\&quot;https://help.clicksend.com/en/articles/42317-delivery-notifications-reports\&quot; target&#x3D;\&quot;_blank\&quot;&gt;delivery report&lt;/a&gt; rule with the Action set to **POLL** in the Dashboard, or use the [**Create SMS Delivery Receipt Rule**](/automations/sms/other/create-sms-delivery-receipt-rule) endpoint.  Control [pagination](/#pagination) with the _page_ and _limit_ query parameters to specify the page of results and the number of items returned.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [Integer] :page The page number to retrieve. Use this parameter to navigate through the [pagination](/#pagination) results. The default value is 1.
  # @option opts [Integer] :limit The number of items to return per page. This parameter controls the size of each page of results. The default value is 15.
  # @return [ViewSmsReceipts]
  describe 'view_sms_receipts test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_sms_templates
  # View SMS Templates
  # Use this endpoint to retrieve &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/9z9uloaz8y-sms-templates-for-different-industries\&quot; target&#x3D;\&quot;_blank\&quot;&gt;SMS templates&lt;/a&gt;. You can filter the SMS templates result using the query parameters.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @option opts [Integer] :page The page number to retrieve. Use this parameter to navigate through the [pagination](/#pagination) results. The default value is 1.
  # @option opts [Integer] :limit The number of items to return per page. This parameter controls the size of each page of results. The default value is 15.
  # @option opts [String] :q Allows filtering of results based on your search criteria. The query should be in the format &#x60;field_name:value&#x60;.  1. **Field Name**: The field within the SMS history you want to filter by. You can use the following fields:    - _template_id_ : The ID of the template   - _template_name_ : The name of the template   - _body_ : The body content of the template.          2. **Value**: The text or keyword you&#39;re searching for within the specified field. If left empty after the colon, the filter will look for all templates with any value in the **Field Name**.      For example, if you are searching for the template with the name of _sample_name_, the final query would look like this:     &#x60;q&#x3D;template_name:sample_name&#x60;  &lt;div class&#x3D;\&quot;info-box\&quot;&gt;   &lt;h4&gt;&lt;i class&#x3D;\&quot;fas fa-info-circle\&quot;&gt;&lt;/i&gt; Note:&lt;/h4&gt;   &lt;div&gt;    &lt;p&gt;Some characters have to be encoded. For example, if you are searching for SMS sent from the phone number +61437085284, your search query q would be:&lt;br/&gt;&lt;/p&gt;     &lt;ul&gt;       &lt;li&gt;q&#x3D;from:%2B61437085284&lt;/li&gt;     &lt;/ul&gt;     &lt;p&gt;You can use the &lt;a href&#x3D;\&quot;https://www.urlencoder.org/\&quot; target&#x3D;\&quot;_blank\&quot;&gt;URL encoder&lt;/a&gt; to encode the text. If a character is not an alphanumeric character (A-Z, a-z, 0-9), it is typically either reserved or unsafe and should be encoded.&lt;/p&gt;   &lt;/div&gt; &lt;/div&gt;
  # @option opts [String] :order_by Specifies the field and order to sort the results by.  The value is composed of the field name followed by a colon and the sort direction (_asc_ for ascending or _desc_ for descending).  The default sort order is by _template_id_ in ascending order. You can use the following fields:      - _template_id_ : The ID of the Template - _template_name_ : The name of the Template - _body_ : The body content of the Template  For example, if you want to order by the _template_id_ in descending order, the query would look like this:    &#x60;order_by&#x3D;template_id:desc&#x60;
  # @return [ViewSmsTemplates]
  describe 'view_sms_templates test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for view_specific_sms_receipt
  # View Specific SMS Receipt
  # Use this endpoint to retrieve a specific &lt;a href&#x3D;\&quot;https://help.clicksend.com/article/49eq1qdcui-how-do-i-receive-sms-delivery-receipts-delivery-status-updates\&quot; target&#x3D;\&quot;_blank\&quot;&gt;SMS delivery receipt&lt;/a&gt;, including those that have been marked as read. When you send an SMS, a delivery receipt is generated and can be received.  This endpoint enables you to retrieve those receipts.
  # @param message_id The _message_id_ of the SMS delivery receipt to retrieve
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [ViewSpecificSmsReceipt]
  describe 'view_specific_sms_receipt test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
