=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'spec_helper'
require 'json'

# Unit tests for ClickSend::UrlShorteningApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UrlShorteningApi' do
  before do
    # run before each test
    @api_instance = ClickSend::UrlShorteningApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UrlShorteningApi' do
    it 'should create an instance of UrlShorteningApi' do
      expect(@api_instance).to be_instance_of(ClickSend::UrlShorteningApi)
    end
  end

  # unit tests for short_url_get_statistics
  # Get Statistics
  # Use this endpoint to get the aggregated statistics for a shortened URL. This allows you to track the total number of clicks on the link. You can gather details such as the device type and where it was opened from as well.
  # @param source Source of the request.
  # @param source_id ID of the source (e.g. message ID).
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [GetStatistics]
  describe 'short_url_get_statistics test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for short_url_get_tracking
  # Get Tracking
  # Use this endpoint to track how individual recipients interact with the link.  It returns data from the most recent click, including statistics such as how many times they’ve visited the link and when it was last opened. To use this endpoint, reference the _long_url_id_ provided in the [GET /short-url/statistics](/messaging/url-shortening/other/short-url-get-statistics) endpoint.
  # @param long_url_id ID of the long URL (uniquely defined by the source, source ID, and long URL). Obtained from the GET statistics endpoint.
  # @param [Hash] opts the optional parameters
  # @option opts [String] :content_type 
  # @return [GetTracking]
  describe 'short_url_get_tracking test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
