=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ClickSend
  class GetTracking < ApiModelBase
    # Total number of short URLs associated with the long URL ID
    attr_accessor :total

    # The limit of tracking data per page
    attr_accessor :per_page

    # The number of data in the current page
    attr_accessor :current_page_size

    # Link to the previous page. This attribute will not be present if there is no previous page.
    attr_accessor :prev_page_url

    # Link to the next page. This attribute will not be present if there is no next page.
    attr_accessor :next_page_url

    # Tracking data of the short URLs associated with the specified long URL ID. Note that only the data from the most recent click of the recipient (country, region, device, browser, and os) is recorded.
    attr_accessor :data

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'total' => :'total',
        :'per_page' => :'per_page',
        :'current_page_size' => :'current_page_size',
        :'prev_page_url' => :'prev_page_url',
        :'next_page_url' => :'next_page_url',
        :'data' => :'data'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'total' => :'Float',
        :'per_page' => :'Float',
        :'current_page_size' => :'Float',
        :'prev_page_url' => :'String',
        :'next_page_url' => :'String',
        :'data' => :'Array<GetTrackingDataInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ClickSend::GetTracking` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ClickSend::GetTracking`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      end

      if attributes.key?(:'per_page')
        self.per_page = attributes[:'per_page']
      end

      if attributes.key?(:'current_page_size')
        self.current_page_size = attributes[:'current_page_size']
      end

      if attributes.key?(:'prev_page_url')
        self.prev_page_url = attributes[:'prev_page_url']
      end

      if attributes.key?(:'next_page_url')
        self.next_page_url = attributes[:'next_page_url']
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Array)
          self.data = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@per_page.nil? && @per_page > 100
        invalid_properties.push('invalid value for "per_page", must be smaller than or equal to 100.')
      end

      if !@current_page_size.nil? && @current_page_size > 100
        invalid_properties.push('invalid value for "current_page_size", must be smaller than or equal to 100.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@per_page.nil? && @per_page > 100
      return false if !@current_page_size.nil? && @current_page_size > 100
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] per_page Value to be assigned
    def per_page=(per_page)
      if per_page.nil?
        fail ArgumentError, 'per_page cannot be nil'
      end

      if per_page > 100
        fail ArgumentError, 'invalid value for "per_page", must be smaller than or equal to 100.'
      end

      @per_page = per_page
    end

    # Custom attribute writer method with validation
    # @param [Object] current_page_size Value to be assigned
    def current_page_size=(current_page_size)
      if current_page_size.nil?
        fail ArgumentError, 'current_page_size cannot be nil'
      end

      if current_page_size > 100
        fail ArgumentError, 'invalid value for "current_page_size", must be smaller than or equal to 100.'
      end

      @current_page_size = current_page_size
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          total == o.total &&
          per_page == o.per_page &&
          current_page_size == o.current_page_size &&
          prev_page_url == o.prev_page_url &&
          next_page_url == o.next_page_url &&
          data == o.data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [total, per_page, current_page_size, prev_page_url, next_page_url, data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
