=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ClickSend
  # Optional registration data for number compliance
  class BuyNumberRequestRegistrationData < ApiModelBase
    # Name of the business (2 - 100 characters)
    attr_accessor :business_name

    # Business address (5 - 150 characters)
    attr_accessor :business_address

    # Suburb/City (2 - 50 characters)
    attr_accessor :suburb

    # Postal code (2 - 20 characters)
    attr_accessor :postcode

    # State/Province (2 - 50 characters)
    attr_accessor :state

    # Contact person name (2 - 100 characters)
    attr_accessor :contact_name

    # Contact phone number (valid local or international phone number)
    attr_accessor :contact_number

    # Country code (ISO 3166-1 alpha-2)
    attr_accessor :country

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'business_name' => :'business_name',
        :'business_address' => :'business_address',
        :'suburb' => :'suburb',
        :'postcode' => :'postcode',
        :'state' => :'state',
        :'contact_name' => :'contact_name',
        :'contact_number' => :'contact_number',
        :'country' => :'country'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'business_name' => :'String',
        :'business_address' => :'String',
        :'suburb' => :'String',
        :'postcode' => :'String',
        :'state' => :'String',
        :'contact_name' => :'String',
        :'contact_number' => :'String',
        :'country' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ClickSend::BuyNumberRequestRegistrationData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ClickSend::BuyNumberRequestRegistrationData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'business_name')
        self.business_name = attributes[:'business_name']
      else
        self.business_name = nil
      end

      if attributes.key?(:'business_address')
        self.business_address = attributes[:'business_address']
      else
        self.business_address = nil
      end

      if attributes.key?(:'suburb')
        self.suburb = attributes[:'suburb']
      else
        self.suburb = nil
      end

      if attributes.key?(:'postcode')
        self.postcode = attributes[:'postcode']
      else
        self.postcode = nil
      end

      if attributes.key?(:'state')
        self.state = attributes[:'state']
      else
        self.state = nil
      end

      if attributes.key?(:'contact_name')
        self.contact_name = attributes[:'contact_name']
      else
        self.contact_name = nil
      end

      if attributes.key?(:'contact_number')
        self.contact_number = attributes[:'contact_number']
      else
        self.contact_number = nil
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      else
        self.country = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @business_name.nil?
        invalid_properties.push('invalid value for "business_name", business_name cannot be nil.')
      end

      if @business_name.to_s.length > 100
        invalid_properties.push('invalid value for "business_name", the character length must be smaller than or equal to 100.')
      end

      if @business_name.to_s.length < 2
        invalid_properties.push('invalid value for "business_name", the character length must be greater than or equal to 2.')
      end

      if @business_address.nil?
        invalid_properties.push('invalid value for "business_address", business_address cannot be nil.')
      end

      if @business_address.to_s.length > 150
        invalid_properties.push('invalid value for "business_address", the character length must be smaller than or equal to 150.')
      end

      if @business_address.to_s.length < 5
        invalid_properties.push('invalid value for "business_address", the character length must be greater than or equal to 5.')
      end

      if @suburb.nil?
        invalid_properties.push('invalid value for "suburb", suburb cannot be nil.')
      end

      if @suburb.to_s.length > 50
        invalid_properties.push('invalid value for "suburb", the character length must be smaller than or equal to 50.')
      end

      if @suburb.to_s.length < 2
        invalid_properties.push('invalid value for "suburb", the character length must be greater than or equal to 2.')
      end

      if @postcode.nil?
        invalid_properties.push('invalid value for "postcode", postcode cannot be nil.')
      end

      if @postcode.to_s.length > 20
        invalid_properties.push('invalid value for "postcode", the character length must be smaller than or equal to 20.')
      end

      if @postcode.to_s.length < 2
        invalid_properties.push('invalid value for "postcode", the character length must be greater than or equal to 2.')
      end

      if @state.nil?
        invalid_properties.push('invalid value for "state", state cannot be nil.')
      end

      if @state.to_s.length > 50
        invalid_properties.push('invalid value for "state", the character length must be smaller than or equal to 50.')
      end

      if @state.to_s.length < 2
        invalid_properties.push('invalid value for "state", the character length must be greater than or equal to 2.')
      end

      if @contact_name.nil?
        invalid_properties.push('invalid value for "contact_name", contact_name cannot be nil.')
      end

      if @contact_name.to_s.length > 100
        invalid_properties.push('invalid value for "contact_name", the character length must be smaller than or equal to 100.')
      end

      if @contact_name.to_s.length < 2
        invalid_properties.push('invalid value for "contact_name", the character length must be greater than or equal to 2.')
      end

      if @contact_number.nil?
        invalid_properties.push('invalid value for "contact_number", contact_number cannot be nil.')
      end

      pattern = Regexp.new(/^\+?[1-9]\d{1,14}$/)
      if @contact_number !~ pattern
        invalid_properties.push("invalid value for \"contact_number\", must conform to the pattern #{pattern}.")
      end

      if @country.nil?
        invalid_properties.push('invalid value for "country", country cannot be nil.')
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if @country !~ pattern
        invalid_properties.push("invalid value for \"country\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @business_name.nil?
      return false if @business_name.to_s.length > 100
      return false if @business_name.to_s.length < 2
      return false if @business_address.nil?
      return false if @business_address.to_s.length > 150
      return false if @business_address.to_s.length < 5
      return false if @suburb.nil?
      return false if @suburb.to_s.length > 50
      return false if @suburb.to_s.length < 2
      return false if @postcode.nil?
      return false if @postcode.to_s.length > 20
      return false if @postcode.to_s.length < 2
      return false if @state.nil?
      return false if @state.to_s.length > 50
      return false if @state.to_s.length < 2
      return false if @contact_name.nil?
      return false if @contact_name.to_s.length > 100
      return false if @contact_name.to_s.length < 2
      return false if @contact_number.nil?
      return false if @contact_number !~ Regexp.new(/^\+?[1-9]\d{1,14}$/)
      return false if @country.nil?
      return false if @country !~ Regexp.new(/^[A-Z]{2}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] business_name Value to be assigned
    def business_name=(business_name)
      if business_name.nil?
        fail ArgumentError, 'business_name cannot be nil'
      end

      if business_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "business_name", the character length must be smaller than or equal to 100.'
      end

      if business_name.to_s.length < 2
        fail ArgumentError, 'invalid value for "business_name", the character length must be greater than or equal to 2.'
      end

      @business_name = business_name
    end

    # Custom attribute writer method with validation
    # @param [Object] business_address Value to be assigned
    def business_address=(business_address)
      if business_address.nil?
        fail ArgumentError, 'business_address cannot be nil'
      end

      if business_address.to_s.length > 150
        fail ArgumentError, 'invalid value for "business_address", the character length must be smaller than or equal to 150.'
      end

      if business_address.to_s.length < 5
        fail ArgumentError, 'invalid value for "business_address", the character length must be greater than or equal to 5.'
      end

      @business_address = business_address
    end

    # Custom attribute writer method with validation
    # @param [Object] suburb Value to be assigned
    def suburb=(suburb)
      if suburb.nil?
        fail ArgumentError, 'suburb cannot be nil'
      end

      if suburb.to_s.length > 50
        fail ArgumentError, 'invalid value for "suburb", the character length must be smaller than or equal to 50.'
      end

      if suburb.to_s.length < 2
        fail ArgumentError, 'invalid value for "suburb", the character length must be greater than or equal to 2.'
      end

      @suburb = suburb
    end

    # Custom attribute writer method with validation
    # @param [Object] postcode Value to be assigned
    def postcode=(postcode)
      if postcode.nil?
        fail ArgumentError, 'postcode cannot be nil'
      end

      if postcode.to_s.length > 20
        fail ArgumentError, 'invalid value for "postcode", the character length must be smaller than or equal to 20.'
      end

      if postcode.to_s.length < 2
        fail ArgumentError, 'invalid value for "postcode", the character length must be greater than or equal to 2.'
      end

      @postcode = postcode
    end

    # Custom attribute writer method with validation
    # @param [Object] state Value to be assigned
    def state=(state)
      if state.nil?
        fail ArgumentError, 'state cannot be nil'
      end

      if state.to_s.length > 50
        fail ArgumentError, 'invalid value for "state", the character length must be smaller than or equal to 50.'
      end

      if state.to_s.length < 2
        fail ArgumentError, 'invalid value for "state", the character length must be greater than or equal to 2.'
      end

      @state = state
    end

    # Custom attribute writer method with validation
    # @param [Object] contact_name Value to be assigned
    def contact_name=(contact_name)
      if contact_name.nil?
        fail ArgumentError, 'contact_name cannot be nil'
      end

      if contact_name.to_s.length > 100
        fail ArgumentError, 'invalid value for "contact_name", the character length must be smaller than or equal to 100.'
      end

      if contact_name.to_s.length < 2
        fail ArgumentError, 'invalid value for "contact_name", the character length must be greater than or equal to 2.'
      end

      @contact_name = contact_name
    end

    # Custom attribute writer method with validation
    # @param [Object] contact_number Value to be assigned
    def contact_number=(contact_number)
      if contact_number.nil?
        fail ArgumentError, 'contact_number cannot be nil'
      end

      pattern = Regexp.new(/^\+?[1-9]\d{1,14}$/)
      if contact_number !~ pattern
        fail ArgumentError, "invalid value for \"contact_number\", must conform to the pattern #{pattern}."
      end

      @contact_number = contact_number
    end

    # Custom attribute writer method with validation
    # @param [Object] country Value to be assigned
    def country=(country)
      if country.nil?
        fail ArgumentError, 'country cannot be nil'
      end

      pattern = Regexp.new(/^[A-Z]{2}$/)
      if country !~ pattern
        fail ArgumentError, "invalid value for \"country\", must conform to the pattern #{pattern}."
      end

      @country = country
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          business_name == o.business_name &&
          business_address == o.business_address &&
          suburb == o.suburb &&
          postcode == o.postcode &&
          state == o.state &&
          contact_name == o.contact_name &&
          contact_number == o.contact_number &&
          country == o.country
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [business_name, business_address, suburb, postcode, state, contact_name, contact_number, country].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
