=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ClickSend
  class CreateNewContactRequest < ApiModelBase
    attr_accessor :phone_number

    attr_accessor :first_name

    attr_accessor :last_name

    attr_accessor :custom_1

    attr_accessor :custom_2

    attr_accessor :custom_3

    attr_accessor :custom_4

    attr_accessor :date_added

    attr_accessor :fax_number

    attr_accessor :organization_name

    attr_accessor :email

    attr_accessor :address_line_1

    attr_accessor :address_line_2

    attr_accessor :address_city

    attr_accessor :address_state

    attr_accessor :address_postal_code

    attr_accessor :address_country

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'phone_number' => :'phone_number',
        :'first_name' => :'first_name',
        :'last_name' => :'last_name',
        :'custom_1' => :'custom_1',
        :'custom_2' => :'custom_2',
        :'custom_3' => :'custom_3',
        :'custom_4' => :'custom_4',
        :'date_added' => :'date_added',
        :'fax_number' => :'fax_number',
        :'organization_name' => :'organization_name',
        :'email' => :'email',
        :'address_line_1' => :'address_line_1',
        :'address_line_2' => :'address_line_2',
        :'address_city' => :'address_city',
        :'address_state' => :'address_state',
        :'address_postal_code' => :'address_postal_code',
        :'address_country' => :'address_country'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'phone_number' => :'String',
        :'first_name' => :'String',
        :'last_name' => :'String',
        :'custom_1' => :'String',
        :'custom_2' => :'String',
        :'custom_3' => :'String',
        :'custom_4' => :'String',
        :'date_added' => :'String',
        :'fax_number' => :'String',
        :'organization_name' => :'String',
        :'email' => :'String',
        :'address_line_1' => :'String',
        :'address_line_2' => :'String',
        :'address_city' => :'String',
        :'address_state' => :'String',
        :'address_postal_code' => :'String',
        :'address_country' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'date_added',
        :'fax_number',
        :'organization_name',
        :'email',
        :'address_line_1',
        :'address_line_2',
        :'address_city',
        :'address_state',
        :'address_postal_code',
        :'address_country'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ClickSend::CreateNewContactRequest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ClickSend::CreateNewContactRequest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'phone_number')
        self.phone_number = attributes[:'phone_number']
      end

      if attributes.key?(:'first_name')
        self.first_name = attributes[:'first_name']
      end

      if attributes.key?(:'last_name')
        self.last_name = attributes[:'last_name']
      end

      if attributes.key?(:'custom_1')
        self.custom_1 = attributes[:'custom_1']
      end

      if attributes.key?(:'custom_2')
        self.custom_2 = attributes[:'custom_2']
      end

      if attributes.key?(:'custom_3')
        self.custom_3 = attributes[:'custom_3']
      end

      if attributes.key?(:'custom_4')
        self.custom_4 = attributes[:'custom_4']
      end

      if attributes.key?(:'date_added')
        self.date_added = attributes[:'date_added']
      end

      if attributes.key?(:'fax_number')
        self.fax_number = attributes[:'fax_number']
      end

      if attributes.key?(:'organization_name')
        self.organization_name = attributes[:'organization_name']
      end

      if attributes.key?(:'email')
        self.email = attributes[:'email']
      end

      if attributes.key?(:'address_line_1')
        self.address_line_1 = attributes[:'address_line_1']
      end

      if attributes.key?(:'address_line_2')
        self.address_line_2 = attributes[:'address_line_2']
      end

      if attributes.key?(:'address_city')
        self.address_city = attributes[:'address_city']
      end

      if attributes.key?(:'address_state')
        self.address_state = attributes[:'address_state']
      end

      if attributes.key?(:'address_postal_code')
        self.address_postal_code = attributes[:'address_postal_code']
      end

      if attributes.key?(:'address_country')
        self.address_country = attributes[:'address_country']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          phone_number == o.phone_number &&
          first_name == o.first_name &&
          last_name == o.last_name &&
          custom_1 == o.custom_1 &&
          custom_2 == o.custom_2 &&
          custom_3 == o.custom_3 &&
          custom_4 == o.custom_4 &&
          date_added == o.date_added &&
          fax_number == o.fax_number &&
          organization_name == o.organization_name &&
          email == o.email &&
          address_line_1 == o.address_line_1 &&
          address_line_2 == o.address_line_2 &&
          address_city == o.address_city &&
          address_state == o.address_state &&
          address_postal_code == o.address_postal_code &&
          address_country == o.address_country
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [phone_number, first_name, last_name, custom_1, custom_2, custom_3, custom_4, date_added, fax_number, organization_name, email, address_line_1, address_line_2, address_city, address_state, address_postal_code, address_country].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
