=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ClickSend
  class PostcardRecipient < ApiModelBase
    # The ID of the user.
    attr_accessor :user_id

    # The ID of the subaccount.
    attr_accessor :subaccount_id

    # The ID of the message.
    attr_accessor :message_id

    # The name associated with the address.
    attr_accessor :address_name

    # The first line of the address.
    attr_accessor :address_line_1

    # The second line of the address.
    attr_accessor :address_line_2

    # The city of the address.
    attr_accessor :address_city

    # The state of the address.
    attr_accessor :address_state

    # The postal code of the address.
    attr_accessor :address_postal_code

    # The country code of the address.
    attr_accessor :address_country

    # The ID of the return address.
    attr_accessor :return_address_id

    # The filename of the letter file.
    attr_accessor :letter_file_name

    # The schedule timestamp of the message.
    attr_accessor :schedule

    # The IP address associated with the message.
    attr_accessor :ip_address

    # The source of the message.
    attr_accessor :source

    # The price of posting the message.
    attr_accessor :post_price

    # The priority of the message.
    attr_accessor :priority

    # The status of the message.
    attr_accessor :status

    # The timestamp when the message was added.
    attr_accessor :date_added

    # The URL of the file associated with the message.
    attr_accessor :_file_url

    attr_accessor :_return_address

    # The API username associated with the message.
    attr_accessor :_api_username

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'user_id' => :'user_id',
        :'subaccount_id' => :'subaccount_id',
        :'message_id' => :'message_id',
        :'address_name' => :'address_name',
        :'address_line_1' => :'address_line_1',
        :'address_line_2' => :'address_line_2',
        :'address_city' => :'address_city',
        :'address_state' => :'address_state',
        :'address_postal_code' => :'address_postal_code',
        :'address_country' => :'address_country',
        :'return_address_id' => :'return_address_id',
        :'letter_file_name' => :'letter_file_name',
        :'schedule' => :'schedule',
        :'ip_address' => :'ip_address',
        :'source' => :'source',
        :'post_price' => :'post_price',
        :'priority' => :'priority',
        :'status' => :'status',
        :'date_added' => :'date_added',
        :'_file_url' => :'_file_url',
        :'_return_address' => :'_return_address',
        :'_api_username' => :'_api_username'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'user_id' => :'Integer',
        :'subaccount_id' => :'Integer',
        :'message_id' => :'String',
        :'address_name' => :'String',
        :'address_line_1' => :'String',
        :'address_line_2' => :'String',
        :'address_city' => :'String',
        :'address_state' => :'String',
        :'address_postal_code' => :'String',
        :'address_country' => :'String',
        :'return_address_id' => :'Integer',
        :'letter_file_name' => :'String',
        :'schedule' => :'Integer',
        :'ip_address' => :'String',
        :'source' => :'String',
        :'post_price' => :'Integer',
        :'priority' => :'Integer',
        :'status' => :'String',
        :'date_added' => :'Integer',
        :'_file_url' => :'String',
        :'_return_address' => :'PostcardRecipientReturnAddress',
        :'_api_username' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ClickSend::PostcardRecipient` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ClickSend::PostcardRecipient`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'subaccount_id')
        self.subaccount_id = attributes[:'subaccount_id']
      end

      if attributes.key?(:'message_id')
        self.message_id = attributes[:'message_id']
      end

      if attributes.key?(:'address_name')
        self.address_name = attributes[:'address_name']
      end

      if attributes.key?(:'address_line_1')
        self.address_line_1 = attributes[:'address_line_1']
      end

      if attributes.key?(:'address_line_2')
        self.address_line_2 = attributes[:'address_line_2']
      end

      if attributes.key?(:'address_city')
        self.address_city = attributes[:'address_city']
      end

      if attributes.key?(:'address_state')
        self.address_state = attributes[:'address_state']
      end

      if attributes.key?(:'address_postal_code')
        self.address_postal_code = attributes[:'address_postal_code']
      end

      if attributes.key?(:'address_country')
        self.address_country = attributes[:'address_country']
      end

      if attributes.key?(:'return_address_id')
        self.return_address_id = attributes[:'return_address_id']
      end

      if attributes.key?(:'letter_file_name')
        self.letter_file_name = attributes[:'letter_file_name']
      end

      if attributes.key?(:'schedule')
        self.schedule = attributes[:'schedule']
      end

      if attributes.key?(:'ip_address')
        self.ip_address = attributes[:'ip_address']
      end

      if attributes.key?(:'source')
        self.source = attributes[:'source']
      end

      if attributes.key?(:'post_price')
        self.post_price = attributes[:'post_price']
      end

      if attributes.key?(:'priority')
        self.priority = attributes[:'priority']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'date_added')
        self.date_added = attributes[:'date_added']
      end

      if attributes.key?(:'_file_url')
        self._file_url = attributes[:'_file_url']
      end

      if attributes.key?(:'_return_address')
        self._return_address = attributes[:'_return_address']
      end

      if attributes.key?(:'_api_username')
        self._api_username = attributes[:'_api_username']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          user_id == o.user_id &&
          subaccount_id == o.subaccount_id &&
          message_id == o.message_id &&
          address_name == o.address_name &&
          address_line_1 == o.address_line_1 &&
          address_line_2 == o.address_line_2 &&
          address_city == o.address_city &&
          address_state == o.address_state &&
          address_postal_code == o.address_postal_code &&
          address_country == o.address_country &&
          return_address_id == o.return_address_id &&
          letter_file_name == o.letter_file_name &&
          schedule == o.schedule &&
          ip_address == o.ip_address &&
          source == o.source &&
          post_price == o.post_price &&
          priority == o.priority &&
          status == o.status &&
          date_added == o.date_added &&
          _file_url == o._file_url &&
          _return_address == o._return_address &&
          _api_username == o._api_username
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [user_id, subaccount_id, message_id, address_name, address_line_1, address_line_2, address_city, address_state, address_postal_code, address_country, return_address_id, letter_file_name, schedule, ip_address, source, post_price, priority, status, date_added, _file_url, _return_address, _api_username].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
