=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ClickSend
  class ViewAccountUsageData < ApiModelBase
    attr_accessor :sms

    attr_accessor :mms

    attr_accessor :voice

    attr_accessor :fax

    attr_accessor :post

    attr_accessor :email

    attr_accessor :email_transactional

    attr_accessor :postcards

    attr_accessor :sms_total

    attr_accessor :voice_total

    attr_accessor :fax_total

    attr_accessor :post_total

    attr_accessor :email_total

    attr_accessor :mms_total

    attr_accessor :email_transactional_total

    attr_accessor :postcards_total

    attr_accessor :_currency

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'sms' => :'sms',
        :'mms' => :'mms',
        :'voice' => :'voice',
        :'fax' => :'fax',
        :'post' => :'post',
        :'email' => :'email',
        :'email_transactional' => :'email_transactional',
        :'postcards' => :'postcards',
        :'sms_total' => :'sms_total',
        :'voice_total' => :'voice_total',
        :'fax_total' => :'fax_total',
        :'post_total' => :'post_total',
        :'email_total' => :'email_total',
        :'mms_total' => :'mms_total',
        :'email_transactional_total' => :'email_transactional_total',
        :'postcards_total' => :'postcards_total',
        :'_currency' => :'_currency'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'sms' => :'Array<ViewAccountUsageDataSmsInner>',
        :'mms' => :'Array<ViewAccountUsageDataMmsInner>',
        :'voice' => :'Array<ViewAccountUsageDataMmsInner>',
        :'fax' => :'Array<ViewAccountUsageDataMmsInner>',
        :'post' => :'Array<ViewAccountUsageDataMmsInner>',
        :'email' => :'Array<ViewAccountUsageDataEmailInner>',
        :'email_transactional' => :'Array<ViewAccountUsageDataEmailInner>',
        :'postcards' => :'Array<ViewAccountUsageDataMmsInner>',
        :'sms_total' => :'ViewAccountUsageDataSmsTotal',
        :'voice_total' => :'ViewAccountUsageDataSmsTotal',
        :'fax_total' => :'ViewAccountUsageDataSmsTotal',
        :'post_total' => :'ViewAccountUsageDataSmsTotal',
        :'email_total' => :'ViewAccountUsageDataEmailTotal',
        :'mms_total' => :'ViewVoiceStatisticsDataTotalOutbound',
        :'email_transactional_total' => :'ViewVoiceStatisticsDataTotalOutbound',
        :'postcards_total' => :'ViewVoiceStatisticsDataTotalOutbound',
        :'_currency' => :'Currency'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ClickSend::ViewAccountUsageData` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ClickSend::ViewAccountUsageData`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'sms')
        if (value = attributes[:'sms']).is_a?(Array)
          self.sms = value
        end
      end

      if attributes.key?(:'mms')
        if (value = attributes[:'mms']).is_a?(Array)
          self.mms = value
        end
      end

      if attributes.key?(:'voice')
        if (value = attributes[:'voice']).is_a?(Array)
          self.voice = value
        end
      end

      if attributes.key?(:'fax')
        if (value = attributes[:'fax']).is_a?(Array)
          self.fax = value
        end
      end

      if attributes.key?(:'post')
        if (value = attributes[:'post']).is_a?(Array)
          self.post = value
        end
      end

      if attributes.key?(:'email')
        if (value = attributes[:'email']).is_a?(Array)
          self.email = value
        end
      end

      if attributes.key?(:'email_transactional')
        if (value = attributes[:'email_transactional']).is_a?(Array)
          self.email_transactional = value
        end
      end

      if attributes.key?(:'postcards')
        if (value = attributes[:'postcards']).is_a?(Array)
          self.postcards = value
        end
      end

      if attributes.key?(:'sms_total')
        self.sms_total = attributes[:'sms_total']
      end

      if attributes.key?(:'voice_total')
        self.voice_total = attributes[:'voice_total']
      end

      if attributes.key?(:'fax_total')
        self.fax_total = attributes[:'fax_total']
      end

      if attributes.key?(:'post_total')
        self.post_total = attributes[:'post_total']
      end

      if attributes.key?(:'email_total')
        self.email_total = attributes[:'email_total']
      end

      if attributes.key?(:'mms_total')
        self.mms_total = attributes[:'mms_total']
      end

      if attributes.key?(:'email_transactional_total')
        self.email_transactional_total = attributes[:'email_transactional_total']
      end

      if attributes.key?(:'postcards_total')
        self.postcards_total = attributes[:'postcards_total']
      end

      if attributes.key?(:'_currency')
        self._currency = attributes[:'_currency']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          sms == o.sms &&
          mms == o.mms &&
          voice == o.voice &&
          fax == o.fax &&
          post == o.post &&
          email == o.email &&
          email_transactional == o.email_transactional &&
          postcards == o.postcards &&
          sms_total == o.sms_total &&
          voice_total == o.voice_total &&
          fax_total == o.fax_total &&
          post_total == o.post_total &&
          email_total == o.email_total &&
          mms_total == o.mms_total &&
          email_transactional_total == o.email_transactional_total &&
          postcards_total == o.postcards_total &&
          _currency == o._currency
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [sms, mms, voice, fax, post, email, email_transactional, postcards, sms_total, voice_total, fax_total, post_total, email_total, mms_total, email_transactional_total, postcards_total, _currency].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
