=begin
#SMS

#You can use the SMS endpoints to send and manage SMS, check the cost of sending SMS, view message history, and more. Integrate them into your system as part of your workflow.  Relevant guides: <a href=\"https://help.clicksend.com/article/h474eseq3a-how-many-characters-can-i-send-in-an-sms\" target=\"_blank\">How many characters can I send in an SMS?</a>, <a href=\"https://help.clicksend.com/article/1hd33n2xns-sms-status-delivery-receipt-expired\" target=\"_blank\">SMS status delivery receipt expired</a>, <a href=\"https://help.clicksend.com/en/articles/42195-unicode-vs-plain-text\" target=\"_blank\">Do you support non-English characters</a>, and <a href=\"https://help.clicksend.com/category/mfdctha7f0-country-specific-features-and-restrictions\" target=\"_blank\">Country Specific Features and Restrictions</a>. <div class=\"info-box\">   <h4><i class=\"fas fa-info-circle\"></i> Note :</h4>   ClickSend is pausing SMS messages containing URLs for new customers. Please remove links from messages to maintain uninterrupted delivery, or <a href=\"https://www.clicksend.com/gb/help/\" target=\"_blank\">contact support</a> to apply for approval for URL messaging. </div>

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.23.0

=end

require 'date'
require 'time'

module ClickSend
  class VoiceMessage < ApiModelBase
    # The date, if applicable. May be null; see also `date_added`.
    attr_accessor :date

    # The Unix timestamp when the message was added.
    attr_accessor :date_added

    # The ID of the list associated with the message, if applicable.
    attr_accessor :list_id

    # The recipient's phone number.
    attr_accessor :to

    # The type of recipient.
    attr_accessor :to_type

    # The body of the message.
    attr_accessor :body

    # The sender's phone number.
    attr_accessor :from

    # The language of the message.
    attr_accessor :lang

    # The voice of the message.
    attr_accessor :voice

    # The timestamp when the message should be sent. Returned as a string since it may be an empty string when no schedule was set.
    attr_accessor :schedule

    # The ID of the message.
    attr_accessor :message_id

    # The number of parts in the message.
    attr_accessor :message_parts

    # The price of the message.
    attr_accessor :message_price

    # The custom string of the message.
    attr_accessor :custom_string

    # The ID of the user.
    attr_accessor :user_id

    # The ID of the subaccount.
    attr_accessor :subaccount_id

    # The country code of the message.
    attr_accessor :country

    # The require input of the message.
    attr_accessor :require_input

    # The machine detection of the message.
    attr_accessor :machine_detection

    # Flag indicating if an answering machine was detected.
    attr_accessor :machine_detected

    # The digits entered by the recipient, if any input was collected.
    attr_accessor :digits

    # The carrier of the recipient's phone number.
    attr_accessor :carrier

    # The status code of the message.
    attr_accessor :status_code

    # A human-readable description of the status.
    attr_accessor :status_text

    # The status of the message.
    attr_accessor :status

    # The API username associated with the message.
    attr_accessor :_api_username

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date' => :'date',
        :'date_added' => :'date_added',
        :'list_id' => :'list_id',
        :'to' => :'to',
        :'to_type' => :'to_type',
        :'body' => :'body',
        :'from' => :'from',
        :'lang' => :'lang',
        :'voice' => :'voice',
        :'schedule' => :'schedule',
        :'message_id' => :'message_id',
        :'message_parts' => :'message_parts',
        :'message_price' => :'message_price',
        :'custom_string' => :'custom_string',
        :'user_id' => :'user_id',
        :'subaccount_id' => :'subaccount_id',
        :'country' => :'country',
        :'require_input' => :'require_input',
        :'machine_detection' => :'machine_detection',
        :'machine_detected' => :'machine_detected',
        :'digits' => :'digits',
        :'carrier' => :'carrier',
        :'status_code' => :'status_code',
        :'status_text' => :'status_text',
        :'status' => :'status',
        :'_api_username' => :'_api_username'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date' => :'String',
        :'date_added' => :'Integer',
        :'list_id' => :'String',
        :'to' => :'String',
        :'to_type' => :'String',
        :'body' => :'String',
        :'from' => :'String',
        :'lang' => :'String',
        :'voice' => :'String',
        :'schedule' => :'String',
        :'message_id' => :'String',
        :'message_parts' => :'String',
        :'message_price' => :'String',
        :'custom_string' => :'String',
        :'user_id' => :'Float',
        :'subaccount_id' => :'Float',
        :'country' => :'String',
        :'require_input' => :'Float',
        :'machine_detection' => :'Float',
        :'machine_detected' => :'Float',
        :'digits' => :'String',
        :'carrier' => :'String',
        :'status_code' => :'String',
        :'status_text' => :'String',
        :'status' => :'String',
        :'_api_username' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'date',
        :'list_id',
        :'from',
        :'machine_detected',
        :'digits',
        :'carrier',
        :'status_code',
        :'status_text',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `ClickSend::VoiceMessage` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `ClickSend::VoiceMessage`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.key?(:'date_added')
        self.date_added = attributes[:'date_added']
      end

      if attributes.key?(:'list_id')
        self.list_id = attributes[:'list_id']
      end

      if attributes.key?(:'to')
        self.to = attributes[:'to']
      end

      if attributes.key?(:'to_type')
        self.to_type = attributes[:'to_type']
      end

      if attributes.key?(:'body')
        self.body = attributes[:'body']
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      end

      if attributes.key?(:'lang')
        self.lang = attributes[:'lang']
      end

      if attributes.key?(:'voice')
        self.voice = attributes[:'voice']
      end

      if attributes.key?(:'schedule')
        self.schedule = attributes[:'schedule']
      end

      if attributes.key?(:'message_id')
        self.message_id = attributes[:'message_id']
      end

      if attributes.key?(:'message_parts')
        self.message_parts = attributes[:'message_parts']
      end

      if attributes.key?(:'message_price')
        self.message_price = attributes[:'message_price']
      end

      if attributes.key?(:'custom_string')
        self.custom_string = attributes[:'custom_string']
      end

      if attributes.key?(:'user_id')
        self.user_id = attributes[:'user_id']
      end

      if attributes.key?(:'subaccount_id')
        self.subaccount_id = attributes[:'subaccount_id']
      end

      if attributes.key?(:'country')
        self.country = attributes[:'country']
      end

      if attributes.key?(:'require_input')
        self.require_input = attributes[:'require_input']
      end

      if attributes.key?(:'machine_detection')
        self.machine_detection = attributes[:'machine_detection']
      end

      if attributes.key?(:'machine_detected')
        self.machine_detected = attributes[:'machine_detected']
      end

      if attributes.key?(:'digits')
        self.digits = attributes[:'digits']
      end

      if attributes.key?(:'carrier')
        self.carrier = attributes[:'carrier']
      end

      if attributes.key?(:'status_code')
        self.status_code = attributes[:'status_code']
      end

      if attributes.key?(:'status_text')
        self.status_text = attributes[:'status_text']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'_api_username')
        self._api_username = attributes[:'_api_username']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date == o.date &&
          date_added == o.date_added &&
          list_id == o.list_id &&
          to == o.to &&
          to_type == o.to_type &&
          body == o.body &&
          from == o.from &&
          lang == o.lang &&
          voice == o.voice &&
          schedule == o.schedule &&
          message_id == o.message_id &&
          message_parts == o.message_parts &&
          message_price == o.message_price &&
          custom_string == o.custom_string &&
          user_id == o.user_id &&
          subaccount_id == o.subaccount_id &&
          country == o.country &&
          require_input == o.require_input &&
          machine_detection == o.machine_detection &&
          machine_detected == o.machine_detected &&
          digits == o.digits &&
          carrier == o.carrier &&
          status_code == o.status_code &&
          status_text == o.status_text &&
          status == o.status &&
          _api_username == o._api_username
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date, date_added, list_id, to, to_type, body, from, lang, voice, schedule, message_id, message_parts, message_price, custom_string, user_id, subaccount_id, country, require_input, machine_detection, machine_detected, digits, carrier, status_code, status_text, status, _api_username].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
